// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaMoR271jnh7DMmskhnuhaxAP2K6pb_tg',
    appId: '1:818780426990:web:9a9d9765f54f5d82e9d9ff',
    messagingSenderId: '818780426990',
    projectId: 'flixtream-3b814',
    authDomain: 'flixtream-3b814.firebaseapp.com',
    databaseURL: 'https://flixtream-3b814-default-rtdb.firebaseio.com',
    storageBucket: 'flixtream-3b814.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJMii0j2wRTPepjIrbLRGVSNeLE-5ee0',
    appId: '1:818780426990:android:5f53df59ccd3dbe3e9d9ff',
    messagingSenderId: '818780426990',
    projectId: 'flixtream-3b814',
    databaseURL: 'https://flixtream-3b814-default-rtdb.firebaseio.com',
    storageBucket: 'flixtream-3b814.firebasestorage.app',
  );
}
